# Generated by Django 3.1.3 on 2020-12-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('orderItem', 'OrderItem')
    ]
